version: '3.5'
services:
  api:
    image: phantoscope/api-server:9746dc5
    ports:
      - "5000:5000"
    environment:
      - MINIO_ADDR=${LOCAL_ADDRESS}:9000
      - UPLOAD_FOLDER=/tmp
      - MILVUS_ADDR=milvus
      - SEARCH_IMAGES_DATABASE_EP=mysql://root:passwd@mysql:3306/search
      - SEARCH_IMAGES_DATABASE_USERNAME=root
      - SEARCH_IMAGES_DATABASE_PASSWD=passwd
      - MILVUS_PORT=19530
      - MINIO_BUCKET_NUM=20
      - MONGO_ADDR=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWD=passwd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - milvus
      - minio
      - mongo
    networks:
      - phantoscope-network
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passwd
    ports:
      - "27017:27017"
    volumes:
      - /mnt/om/mongo:/data/db
    networks:
      - phantoscope-network
  milvus:
    image: milvusdb/milvus:0.10.0-cpu-d061620-5f3c00
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - /mnt/om/milvus/db:/var/lib/milvus/db
    networks:
      - phantoscope-network
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - /mnt/om/minio/data:/data
    command: ["server","/data"]
    networks:
      - phantoscope-network

networks:
  phantoscope-network:
    name: phantoscope_default
