
2

NoOp"serve*1.14.02v1.14.0-rc1-22-gaf24dc9G

init_all_tablesNoOp
(
legacy_init_opNoOp^init_all_tables"&*
predict_imagesŠ
I
images?
image_tensor:0+ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ5
boxes,
detection_boxes:0ÿÿÿÿÿÿÿÿÿd3
scores)
detection_scores:0ÿÿÿÿÿÿÿÿÿd5
classes*
detection_classes:0ÿÿÿÿÿÿÿÿÿdtensorflow/serving/predict